source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ShatteringView_Example', :exclusive => true do
  pod "ShatteringView"
end

target 'ShatteringView_Tests', :exclusive => true do
  pod "ShatteringView"

  
end
